#!/usr/bin/env python
"""Emit a runnable end-to-end chemometrics analysis script.

Given a dataset (a bundled loader name or a file path) and a task, write a
self-contained starter that wires the whole workflow in the correct order:

    load -> split FIRST -> preprocess+model Pipeline -> select LVs by CV
         -> fit on train -> held-out metrics -> fit applicability domain
         -> AD-guarded prediction

The generated script uses only the public chemotools + scikit-learn API (no
dependency on the plugin), so it drops into any project. `# TODO` markers point
at the spoke skill to consult for each decision. This is the orchestrator's one
script; technique depth lives in the specialist skills it routes to.

Importable (:func:`render`) and CLI-runnable::

    python scaffold_analysis.py --dataset fermentation --task regression --out analysis.py
    python scaffold_analysis.py --data spectra.csv --y y.csv --task classification --out run.py
"""

from __future__ import annotations

import argparse

_TEMPLATE = '''#!/usr/bin/env python
"""End-to-end chemometrics analysis (scaffold) — task: {task}.

Generated by the chemometrics-workflow skill. Edit the TODO spots; each names the
spoke skill that owns that decision. Leakage discipline is baked in: split first,
one Pipeline (preprocess + model), fit on train only, AD-guard predictions.
"""
from __future__ import annotations

import numpy as np
from sklearn.model_selection import (KFold, StratifiedKFold, cross_val_score,
                                     train_test_split)
from sklearn.pipeline import Pipeline

# --- preprocessing head (spectral-preprocessing skill) ----------------------
# TODO: choose the correction/scaling chain for your modality. See the
# spectral-preprocessing hub and its spokes (baseline-scatter, smoothing-derivatives).
from chemotools.scatter import StandardNormalVariate
from chemotools.derivative import SavitzkyGolay
{model_import}

{extra_defs}
# === 1. Load =================================================================
{load_block}

# === 2. Split FIRST (everything below is fit on train only) ==================
# TODO: if you have replicate/augmented spectra, split by GROUP and pass
# `groups=` to cross-validation (chemometric-validation skill).
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0{stratify})

# === 3. One Pipeline: preprocess + model (chemometric-modeling skill) ========
def make_pipeline(n_components: int) -> Pipeline:
    return Pipeline([
        ("snv", StandardNormalVariate()),
        ("deriv", SavitzkyGolay(window_length=15, polyorder=2, deriv=1)),
        {model_step}
    ])

# === 4. Select latent variables by CV — 1-SE rule (chemometric-modeling) =====
n_splits = 5
cv = {splitter}
max_lv = min(20, X_train.shape[1], X_train.shape[0] * (n_splits - 1) // n_splits - 1)
rows = []
for nc in range(1, max_lv + 1):
    scores = cross_val_score(make_pipeline(nc), X_train, y_train, cv=cv,
                             scoring="{cv_scoring}")
    rows.append((nc, scores.mean(), scores.std(ddof=1) / np.sqrt(len(scores))))
{select_block}
print(f"selected n_components (1-SE) = {{n_components}}")

# === 5. Fit final model on train ============================================
model = make_pipeline(n_components).fit(X_train, y_train)

# === 6. Held-out metrics (chemometric-validation skill) ======================
{metrics_block}

# === 7. Applicability domain — fit on TRAIN (model-diagnostics skill) ========
from chemotools.outliers import HotellingT2, QResiduals
from sklearn.decomposition import PCA

# TODO: the AD reference space should reflect the deployed model; a handful of
# PCA components on the training spectra is a reasonable default (model-diagnostics).
n_ad = min(10, X_train.shape[0] - 1, X_train.shape[1])
ad_space = PCA(n_components=n_ad).fit(X_train)
t2 = HotellingT2(ad_space, confidence=0.95).fit(X_train)
# `percentile` calibrates the Q limit to the training distribution (~95% of train
# inside by construction); see model-diagnostics for chi-square / jackson-mudholkar.
q = QResiduals(ad_space, confidence=0.95, method="percentile").fit(X_train)

# === 8. AD-guarded prediction ================================================
def predict_guarded(X_new):
    inside = (t2.predict(X_new) == 1) & (q.predict(X_new) == 1)
    preds = model.predict(X_new)
    for i, ok in enumerate(inside):
        if not ok:
            print(f"  sample {{i}}: OUTSIDE applicability domain — prediction unreliable")
    return preds, inside

preds, inside = predict_guarded(X_test)
print(f"{{inside.sum()}} / {{len(inside)}} test samples inside the applicability domain")
'''

_LOAD_BUNDLED = '''from chemotools.datasets import {loader}
_Xdf, _ydf = {loader}()
X, y = _Xdf.to_numpy(), _ydf.to_numpy().ravel()'''

_LOAD_PATH = '''# TODO: point these at your files (see spectral-preprocessing/load_spectra.py
# for the CSV/parquet/npy conventions and x-axis recovery).
import pandas as pd
X = pd.read_csv({data!r}).to_numpy()
y = pd.read_csv({y!r}).to_numpy().ravel()'''

_LOADERS = {"fermentation": "load_fermentation_train", "coffee": "load_coffee"}


def render(task: str, *, dataset: str | None = None, data: str | None = None,
           y: str | None = None) -> str:
    """Return the source of a runnable analysis script for *task*."""
    if task not in ("regression", "classification"):
        raise ValueError("task must be 'regression' or 'classification'.")

    if dataset:
        loader = _LOADERS[dataset]
        load_block = _LOAD_BUNDLED.format(loader=loader)
    elif data and y:
        load_block = _LOAD_PATH.format(data=data, y=y)
    else:
        raise ValueError("Provide either dataset=... or both data=... and y=...")

    if task == "regression":
        model_import = "from chemotools.regression import PLSRegression"
        model_step = '("pls", PLSRegression(n_components=n_components)),'
        splitter = "KFold(n_splits=n_splits, shuffle=True, random_state=0)"
        cv_scoring = "neg_root_mean_squared_error"
        stratify = ""
        select_block = (
            "best_nc, best_m, best_se = max(rows, key=lambda r: r[1])  # neg RMSE: higher better\n"
            "n_components = min(nc for nc, m, _ in rows if m >= best_m - best_se)"
        )
        metrics_block = (
            "from sklearn.metrics import r2_score, root_mean_squared_error\n"
            "y_pred = model.predict(X_test).ravel()\n"
            "rmsep = root_mean_squared_error(y_test, y_pred)\n"
            "rpd = np.std(y_test, ddof=1) / rmsep\n"
            "print(f\"RMSEP {rmsep:.3f}  R2 {r2_score(y_test, y_pred):.3f}  RPD {rpd:.2f}\")"
        )
    else:
        model_import = ""  # _PLSDA is defined at the top of the generated file
        model_step = '("plsda", _PLSDA(n_components=n_components)),'
        splitter = "StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=0)"
        cv_scoring = "accuracy"
        stratify = ", stratify=y"
        select_block = (
            "best_nc, best_m, best_se = max(rows, key=lambda r: r[1])\n"
            "n_components = min(nc for nc, m, _ in rows if m >= best_m - best_se)"
        )
        metrics_block = (
            "from sklearn.metrics import accuracy_score, f1_score, confusion_matrix\n"
            "y_pred = model.predict(X_test)\n"
            "print(f\"accuracy {accuracy_score(y_test, y_pred):.3f}  \"\n"
            "      f\"F1(macro) {f1_score(y_test, y_pred, average='macro'):.3f}\")\n"
            "print(confusion_matrix(y_test, y_pred))"
        )

    extra_defs = _PLSDA_DEF if task == "classification" else ""
    code = _TEMPLATE.format(
        task=task, load_block=load_block, model_import=model_import, extra_defs=extra_defs,
        model_step=model_step, splitter=splitter, cv_scoring=cv_scoring, stratify=stratify,
        select_block=select_block, metrics_block=metrics_block,
    )
    return code


# A minimal, self-contained PLS-DA (one-hot + argmax) for the generated script,
# so it has no dependency on the plugin's fit_model.py. Mirrors the plugin default.
_PLSDA_DEF = '''from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.preprocessing import LabelBinarizer


class _PLSDA(BaseEstimator, ClassifierMixin):
    """PLS-DA: PLS on one-hot classes, predict by argmax (plugin default recipe)."""

    def __init__(self, n_components=2, scale=True):
        self.n_components = n_components
        self.scale = scale

    def fit(self, X, y):
        import numpy as np
        from chemotools.regression import PLSRegression
        self._lb = LabelBinarizer()
        Y = self._lb.fit_transform(y)
        if Y.shape[1] == 1:
            Y = np.hstack([1 - Y, Y])
        self.classes_ = self._lb.classes_
        self.pls_ = PLSRegression(n_components=self.n_components, scale=self.scale).fit(X, Y)
        return self

    def predict(self, X):
        import numpy as np
        return self.classes_[np.argmax(self.pls_.predict(X), axis=1)]


'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    src = parser.add_mutually_exclusive_group(required=True)
    src.add_argument("--dataset", choices=["fermentation", "coffee"])
    src.add_argument("--data", help="Spectra file path (with --y).")
    parser.add_argument("--y", help="Target file path (with --data).")
    parser.add_argument("--task", required=True, choices=["regression", "classification"])
    parser.add_argument("--out", default="analysis.py")
    args = parser.parse_args()

    code = render(args.task, dataset=args.dataset, data=args.data, y=args.y)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(code)
    print(f"wrote {args.out} ({len(code.splitlines())} lines).")
    print("Run it with:  python", args.out)
    print("Then consult the spoke named in each TODO to refine the choices.")


if __name__ == "__main__":
    main()
